# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', '']
quit = ['esc', 'q']

# movement
list_down = ['j', 'down']
list_up = ['k', 'up']
page_down = ['pgdown', '']
page_up = ['pgup', '']
# file panel control
close_file_panel = ['ctrl+w', '']
create_new_file_panel = ['ctrl+n', '']
next_file_panel = ['tab', '']
previous_file_panel = ['shift+tab', '']
toggle_file_preview_panel = ['P', '']
open_sort_options_menu = ['S', '']
toggle_reverse_sort = ['R', '']
# change focus
focus_on_process_bar = ['2', '']
focus_on_sidebar = ['1', '']
focus_on_metadata = ['3', '']
# create file/directory and rename
file_panel_item_create = ['c', '']
file_panel_item_rename = ['r', '']
# file operations
copy_items = ['ctrl+c', '']
paste_items = ['ctrl+v', '']
cut_items = ['shift+ctrl+c', '']
delete_items = ['ctrl+d', '']
# compress and extract
extract_file = ['ctrl+u', '']
compress_file = ['ctrl+z', '']
# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
# other
pinned_directory = ['ctrl+p', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['M', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
open_spf_prompt = ['>', '']
copy_path = ['~', '']
# `CopyPWD` とのことだが良く分からない
# `file_panel_item_create` と被ってる
copy_present_working_directory = ['c', '']
toggle_footer = ['F', '']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['ctrl+g', 'esc']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['h', '']
search_bar = ['ctrl+f', '']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cananot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['J', 'shift+down']
file_panel_select_mode_items_select_up = ['K', 'shift+up']
file_panel_select_all_items = ['A', '']
